size = <0x0 0x10000000>;
subwindow-count = <16>;
sub-window@0 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x0>;
size = <0x0 0x800000>;
};
sub-window@1 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1000000>;
size = <0x0 0x800000>;
};
sub-window@2 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2000000>;
size = <0x0 0x800000>;
};
sub-window@3 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3000000>;
size = <0x0 0x800000>;
};
sub-window@4 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4000000>;
size = <0x0 0x800000>;
};
sub-window@5 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5000000>;
size = <0x0 0x800000>;
};
sub-window@6 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6000000>;
size = <0x0 0x800000>;
};
sub-window@7 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7000000>;
size = <0x0 0x800000>;
};
sub-window@8 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8000000>;
size = <0x0 0x800000>;
};
sub-window@9 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9000000>;
size = <0x0 0x800000>;
};
sub-window@10 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA000000>;
size = <0x0 0x800000>;
};
sub-window@11 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB000000>;
size = <0x0 0x800000>;
};
sub-window@12 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC000000>;
size = <0x0 0x800000>;
};
sub-window@13 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD000000>;
size = <0x0 0x800000>;
};
sub-window@14 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE000000>;
size = <0x0 0x800000>;
};
sub-window@15 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF000000>;
size = <0x0 0x800000>;
};
