size = <0x0 0x10000000>;
subwindow-count = <256>;
sub-window@0 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x0>;
size = <0x0 0x80000>;
};
sub-window@1 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x100000>;
size = <0x0 0x80000>;
};
sub-window@2 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x200000>;
size = <0x0 0x80000>;
};
sub-window@3 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x300000>;
size = <0x0 0x80000>;
};
sub-window@4 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x400000>;
size = <0x0 0x80000>;
};
sub-window@5 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x500000>;
size = <0x0 0x80000>;
};
sub-window@6 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x600000>;
size = <0x0 0x80000>;
};
sub-window@7 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x700000>;
size = <0x0 0x80000>;
};
sub-window@8 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x800000>;
size = <0x0 0x80000>;
};
sub-window@9 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x900000>;
size = <0x0 0x80000>;
};
sub-window@10 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA00000>;
size = <0x0 0x80000>;
};
sub-window@11 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB00000>;
size = <0x0 0x80000>;
};
sub-window@12 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC00000>;
size = <0x0 0x80000>;
};
sub-window@13 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD00000>;
size = <0x0 0x80000>;
};
sub-window@14 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE00000>;
size = <0x0 0x80000>;
};
sub-window@15 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF00000>;
size = <0x0 0x80000>;
};
sub-window@16 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1000000>;
size = <0x0 0x80000>;
};
sub-window@17 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1100000>;
size = <0x0 0x80000>;
};
sub-window@18 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1200000>;
size = <0x0 0x80000>;
};
sub-window@19 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1300000>;
size = <0x0 0x80000>;
};
sub-window@20 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1400000>;
size = <0x0 0x80000>;
};
sub-window@21 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1500000>;
size = <0x0 0x80000>;
};
sub-window@22 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1600000>;
size = <0x0 0x80000>;
};
sub-window@23 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1700000>;
size = <0x0 0x80000>;
};
sub-window@24 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1800000>;
size = <0x0 0x80000>;
};
sub-window@25 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1900000>;
size = <0x0 0x80000>;
};
sub-window@26 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1A00000>;
size = <0x0 0x80000>;
};
sub-window@27 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1B00000>;
size = <0x0 0x80000>;
};
sub-window@28 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1C00000>;
size = <0x0 0x80000>;
};
sub-window@29 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1D00000>;
size = <0x0 0x80000>;
};
sub-window@30 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1E00000>;
size = <0x0 0x80000>;
};
sub-window@31 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x1F00000>;
size = <0x0 0x80000>;
};
sub-window@32 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2000000>;
size = <0x0 0x80000>;
};
sub-window@33 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2100000>;
size = <0x0 0x80000>;
};
sub-window@34 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2200000>;
size = <0x0 0x80000>;
};
sub-window@35 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2300000>;
size = <0x0 0x80000>;
};
sub-window@36 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2400000>;
size = <0x0 0x80000>;
};
sub-window@37 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2500000>;
size = <0x0 0x80000>;
};
sub-window@38 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2600000>;
size = <0x0 0x80000>;
};
sub-window@39 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2700000>;
size = <0x0 0x80000>;
};
sub-window@40 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2800000>;
size = <0x0 0x80000>;
};
sub-window@41 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2900000>;
size = <0x0 0x80000>;
};
sub-window@42 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2A00000>;
size = <0x0 0x80000>;
};
sub-window@43 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2B00000>;
size = <0x0 0x80000>;
};
sub-window@44 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2C00000>;
size = <0x0 0x80000>;
};
sub-window@45 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2D00000>;
size = <0x0 0x80000>;
};
sub-window@46 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2E00000>;
size = <0x0 0x80000>;
};
sub-window@47 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x2F00000>;
size = <0x0 0x80000>;
};
sub-window@48 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3000000>;
size = <0x0 0x80000>;
};
sub-window@49 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3100000>;
size = <0x0 0x80000>;
};
sub-window@50 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3200000>;
size = <0x0 0x80000>;
};
sub-window@51 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3300000>;
size = <0x0 0x80000>;
};
sub-window@52 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3400000>;
size = <0x0 0x80000>;
};
sub-window@53 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3500000>;
size = <0x0 0x80000>;
};
sub-window@54 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3600000>;
size = <0x0 0x80000>;
};
sub-window@55 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3700000>;
size = <0x0 0x80000>;
};
sub-window@56 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3800000>;
size = <0x0 0x80000>;
};
sub-window@57 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3900000>;
size = <0x0 0x80000>;
};
sub-window@58 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3A00000>;
size = <0x0 0x80000>;
};
sub-window@59 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3B00000>;
size = <0x0 0x80000>;
};
sub-window@60 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3C00000>;
size = <0x0 0x80000>;
};
sub-window@61 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3D00000>;
size = <0x0 0x80000>;
};
sub-window@62 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3E00000>;
size = <0x0 0x80000>;
};
sub-window@63 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x3F00000>;
size = <0x0 0x80000>;
};
sub-window@64 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4000000>;
size = <0x0 0x80000>;
};
sub-window@65 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4100000>;
size = <0x0 0x80000>;
};
sub-window@66 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4200000>;
size = <0x0 0x80000>;
};
sub-window@67 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4300000>;
size = <0x0 0x80000>;
};
sub-window@68 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4400000>;
size = <0x0 0x80000>;
};
sub-window@69 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4500000>;
size = <0x0 0x80000>;
};
sub-window@70 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4600000>;
size = <0x0 0x80000>;
};
sub-window@71 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4700000>;
size = <0x0 0x80000>;
};
sub-window@72 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4800000>;
size = <0x0 0x80000>;
};
sub-window@73 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4900000>;
size = <0x0 0x80000>;
};
sub-window@74 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4A00000>;
size = <0x0 0x80000>;
};
sub-window@75 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4B00000>;
size = <0x0 0x80000>;
};
sub-window@76 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4C00000>;
size = <0x0 0x80000>;
};
sub-window@77 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4D00000>;
size = <0x0 0x80000>;
};
sub-window@78 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4E00000>;
size = <0x0 0x80000>;
};
sub-window@79 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x4F00000>;
size = <0x0 0x80000>;
};
sub-window@80 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5000000>;
size = <0x0 0x80000>;
};
sub-window@81 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5100000>;
size = <0x0 0x80000>;
};
sub-window@82 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5200000>;
size = <0x0 0x80000>;
};
sub-window@83 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5300000>;
size = <0x0 0x80000>;
};
sub-window@84 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5400000>;
size = <0x0 0x80000>;
};
sub-window@85 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5500000>;
size = <0x0 0x80000>;
};
sub-window@86 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5600000>;
size = <0x0 0x80000>;
};
sub-window@87 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5700000>;
size = <0x0 0x80000>;
};
sub-window@88 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5800000>;
size = <0x0 0x80000>;
};
sub-window@89 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5900000>;
size = <0x0 0x80000>;
};
sub-window@90 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5A00000>;
size = <0x0 0x80000>;
};
sub-window@91 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5B00000>;
size = <0x0 0x80000>;
};
sub-window@92 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5C00000>;
size = <0x0 0x80000>;
};
sub-window@93 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5D00000>;
size = <0x0 0x80000>;
};
sub-window@94 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5E00000>;
size = <0x0 0x80000>;
};
sub-window@95 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x5F00000>;
size = <0x0 0x80000>;
};
sub-window@96 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6000000>;
size = <0x0 0x80000>;
};
sub-window@97 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6100000>;
size = <0x0 0x80000>;
};
sub-window@98 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6200000>;
size = <0x0 0x80000>;
};
sub-window@99 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6300000>;
size = <0x0 0x80000>;
};
sub-window@100 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6400000>;
size = <0x0 0x80000>;
};
sub-window@101 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6500000>;
size = <0x0 0x80000>;
};
sub-window@102 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6600000>;
size = <0x0 0x80000>;
};
sub-window@103 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6700000>;
size = <0x0 0x80000>;
};
sub-window@104 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6800000>;
size = <0x0 0x80000>;
};
sub-window@105 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6900000>;
size = <0x0 0x80000>;
};
sub-window@106 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6A00000>;
size = <0x0 0x80000>;
};
sub-window@107 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6B00000>;
size = <0x0 0x80000>;
};
sub-window@108 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6C00000>;
size = <0x0 0x80000>;
};
sub-window@109 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6D00000>;
size = <0x0 0x80000>;
};
sub-window@110 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6E00000>;
size = <0x0 0x80000>;
};
sub-window@111 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x6F00000>;
size = <0x0 0x80000>;
};
sub-window@112 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7000000>;
size = <0x0 0x80000>;
};
sub-window@113 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7100000>;
size = <0x0 0x80000>;
};
sub-window@114 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7200000>;
size = <0x0 0x80000>;
};
sub-window@115 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7300000>;
size = <0x0 0x80000>;
};
sub-window@116 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7400000>;
size = <0x0 0x80000>;
};
sub-window@117 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7500000>;
size = <0x0 0x80000>;
};
sub-window@118 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7600000>;
size = <0x0 0x80000>;
};
sub-window@119 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7700000>;
size = <0x0 0x80000>;
};
sub-window@120 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7800000>;
size = <0x0 0x80000>;
};
sub-window@121 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7900000>;
size = <0x0 0x80000>;
};
sub-window@122 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7A00000>;
size = <0x0 0x80000>;
};
sub-window@123 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7B00000>;
size = <0x0 0x80000>;
};
sub-window@124 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7C00000>;
size = <0x0 0x80000>;
};
sub-window@125 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7D00000>;
size = <0x0 0x80000>;
};
sub-window@126 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7E00000>;
size = <0x0 0x80000>;
};
sub-window@127 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x7F00000>;
size = <0x0 0x80000>;
};
sub-window@128 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8000000>;
size = <0x0 0x80000>;
};
sub-window@129 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8100000>;
size = <0x0 0x80000>;
};
sub-window@130 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8200000>;
size = <0x0 0x80000>;
};
sub-window@131 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8300000>;
size = <0x0 0x80000>;
};
sub-window@132 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8400000>;
size = <0x0 0x80000>;
};
sub-window@133 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8500000>;
size = <0x0 0x80000>;
};
sub-window@134 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8600000>;
size = <0x0 0x80000>;
};
sub-window@135 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8700000>;
size = <0x0 0x80000>;
};
sub-window@136 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8800000>;
size = <0x0 0x80000>;
};
sub-window@137 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8900000>;
size = <0x0 0x80000>;
};
sub-window@138 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8A00000>;
size = <0x0 0x80000>;
};
sub-window@139 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8B00000>;
size = <0x0 0x80000>;
};
sub-window@140 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8C00000>;
size = <0x0 0x80000>;
};
sub-window@141 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8D00000>;
size = <0x0 0x80000>;
};
sub-window@142 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8E00000>;
size = <0x0 0x80000>;
};
sub-window@143 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x8F00000>;
size = <0x0 0x80000>;
};
sub-window@144 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9000000>;
size = <0x0 0x80000>;
};
sub-window@145 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9100000>;
size = <0x0 0x80000>;
};
sub-window@146 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9200000>;
size = <0x0 0x80000>;
};
sub-window@147 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9300000>;
size = <0x0 0x80000>;
};
sub-window@148 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9400000>;
size = <0x0 0x80000>;
};
sub-window@149 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9500000>;
size = <0x0 0x80000>;
};
sub-window@150 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9600000>;
size = <0x0 0x80000>;
};
sub-window@151 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9700000>;
size = <0x0 0x80000>;
};
sub-window@152 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9800000>;
size = <0x0 0x80000>;
};
sub-window@153 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9900000>;
size = <0x0 0x80000>;
};
sub-window@154 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9A00000>;
size = <0x0 0x80000>;
};
sub-window@155 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9B00000>;
size = <0x0 0x80000>;
};
sub-window@156 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9C00000>;
size = <0x0 0x80000>;
};
sub-window@157 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9D00000>;
size = <0x0 0x80000>;
};
sub-window@158 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9E00000>;
size = <0x0 0x80000>;
};
sub-window@159 {
compatible = "dma-subwindow";
guest-addr = <0x0 0x9F00000>;
size = <0x0 0x80000>;
};
sub-window@160 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA000000>;
size = <0x0 0x80000>;
};
sub-window@161 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA100000>;
size = <0x0 0x80000>;
};
sub-window@162 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA200000>;
size = <0x0 0x80000>;
};
sub-window@163 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA300000>;
size = <0x0 0x80000>;
};
sub-window@164 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA400000>;
size = <0x0 0x80000>;
};
sub-window@165 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA500000>;
size = <0x0 0x80000>;
};
sub-window@166 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA600000>;
size = <0x0 0x80000>;
};
sub-window@167 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA700000>;
size = <0x0 0x80000>;
};
sub-window@168 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA800000>;
size = <0x0 0x80000>;
};
sub-window@169 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xA900000>;
size = <0x0 0x80000>;
};
sub-window@170 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xAA00000>;
size = <0x0 0x80000>;
};
sub-window@171 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xAB00000>;
size = <0x0 0x80000>;
};
sub-window@172 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xAC00000>;
size = <0x0 0x80000>;
};
sub-window@173 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xAD00000>;
size = <0x0 0x80000>;
};
sub-window@174 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xAE00000>;
size = <0x0 0x80000>;
};
sub-window@175 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xAF00000>;
size = <0x0 0x80000>;
};
sub-window@176 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB000000>;
size = <0x0 0x80000>;
};
sub-window@177 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB100000>;
size = <0x0 0x80000>;
};
sub-window@178 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB200000>;
size = <0x0 0x80000>;
};
sub-window@179 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB300000>;
size = <0x0 0x80000>;
};
sub-window@180 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB400000>;
size = <0x0 0x80000>;
};
sub-window@181 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB500000>;
size = <0x0 0x80000>;
};
sub-window@182 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB600000>;
size = <0x0 0x80000>;
};
sub-window@183 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB700000>;
size = <0x0 0x80000>;
};
sub-window@184 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB800000>;
size = <0x0 0x80000>;
};
sub-window@185 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xB900000>;
size = <0x0 0x80000>;
};
sub-window@186 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xBA00000>;
size = <0x0 0x80000>;
};
sub-window@187 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xBB00000>;
size = <0x0 0x80000>;
};
sub-window@188 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xBC00000>;
size = <0x0 0x80000>;
};
sub-window@189 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xBD00000>;
size = <0x0 0x80000>;
};
sub-window@190 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xBE00000>;
size = <0x0 0x80000>;
};
sub-window@191 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xBF00000>;
size = <0x0 0x80000>;
};
sub-window@192 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC000000>;
size = <0x0 0x80000>;
};
sub-window@193 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC100000>;
size = <0x0 0x80000>;
};
sub-window@194 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC200000>;
size = <0x0 0x80000>;
};
sub-window@195 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC300000>;
size = <0x0 0x80000>;
};
sub-window@196 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC400000>;
size = <0x0 0x80000>;
};
sub-window@197 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC500000>;
size = <0x0 0x80000>;
};
sub-window@198 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC600000>;
size = <0x0 0x80000>;
};
sub-window@199 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC700000>;
size = <0x0 0x80000>;
};
sub-window@200 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC800000>;
size = <0x0 0x80000>;
};
sub-window@201 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xC900000>;
size = <0x0 0x80000>;
};
sub-window@202 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xCA00000>;
size = <0x0 0x80000>;
};
sub-window@203 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xCB00000>;
size = <0x0 0x80000>;
};
sub-window@204 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xCC00000>;
size = <0x0 0x80000>;
};
sub-window@205 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xCD00000>;
size = <0x0 0x80000>;
};
sub-window@206 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xCE00000>;
size = <0x0 0x80000>;
};
sub-window@207 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xCF00000>;
size = <0x0 0x80000>;
};
sub-window@208 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD000000>;
size = <0x0 0x80000>;
};
sub-window@209 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD100000>;
size = <0x0 0x80000>;
};
sub-window@210 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD200000>;
size = <0x0 0x80000>;
};
sub-window@211 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD300000>;
size = <0x0 0x80000>;
};
sub-window@212 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD400000>;
size = <0x0 0x80000>;
};
sub-window@213 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD500000>;
size = <0x0 0x80000>;
};
sub-window@214 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD600000>;
size = <0x0 0x80000>;
};
sub-window@215 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD700000>;
size = <0x0 0x80000>;
};
sub-window@216 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD800000>;
size = <0x0 0x80000>;
};
sub-window@217 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xD900000>;
size = <0x0 0x80000>;
};
sub-window@218 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xDA00000>;
size = <0x0 0x80000>;
};
sub-window@219 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xDB00000>;
size = <0x0 0x80000>;
};
sub-window@220 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xDC00000>;
size = <0x0 0x80000>;
};
sub-window@221 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xDD00000>;
size = <0x0 0x80000>;
};
sub-window@222 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xDE00000>;
size = <0x0 0x80000>;
};
sub-window@223 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xDF00000>;
size = <0x0 0x80000>;
};
sub-window@224 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE000000>;
size = <0x0 0x80000>;
};
sub-window@225 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE100000>;
size = <0x0 0x80000>;
};
sub-window@226 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE200000>;
size = <0x0 0x80000>;
};
sub-window@227 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE300000>;
size = <0x0 0x80000>;
};
sub-window@228 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE400000>;
size = <0x0 0x80000>;
};
sub-window@229 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE500000>;
size = <0x0 0x80000>;
};
sub-window@230 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE600000>;
size = <0x0 0x80000>;
};
sub-window@231 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE700000>;
size = <0x0 0x80000>;
};
sub-window@232 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE800000>;
size = <0x0 0x80000>;
};
sub-window@233 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xE900000>;
size = <0x0 0x80000>;
};
sub-window@234 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xEA00000>;
size = <0x0 0x80000>;
};
sub-window@235 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xEB00000>;
size = <0x0 0x80000>;
};
sub-window@236 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xEC00000>;
size = <0x0 0x80000>;
};
sub-window@237 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xED00000>;
size = <0x0 0x80000>;
};
sub-window@238 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xEE00000>;
size = <0x0 0x80000>;
};
sub-window@239 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xEF00000>;
size = <0x0 0x80000>;
};
sub-window@240 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF000000>;
size = <0x0 0x80000>;
};
sub-window@241 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF100000>;
size = <0x0 0x80000>;
};
sub-window@242 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF200000>;
size = <0x0 0x80000>;
};
sub-window@243 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF300000>;
size = <0x0 0x80000>;
};
sub-window@244 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF400000>;
size = <0x0 0x80000>;
};
sub-window@245 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF500000>;
size = <0x0 0x80000>;
};
sub-window@246 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF600000>;
size = <0x0 0x80000>;
};
sub-window@247 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF700000>;
size = <0x0 0x80000>;
};
sub-window@248 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF800000>;
size = <0x0 0x80000>;
};
sub-window@249 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xF900000>;
size = <0x0 0x80000>;
};
sub-window@250 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xFA00000>;
size = <0x0 0x80000>;
};
sub-window@251 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xFB00000>;
size = <0x0 0x80000>;
};
sub-window@252 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xFC00000>;
size = <0x0 0x80000>;
};
sub-window@253 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xFD00000>;
size = <0x0 0x80000>;
};
sub-window@254 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xFE00000>;
size = <0x0 0x80000>;
};
sub-window@255 {
compatible = "dma-subwindow";
guest-addr = <0x0 0xFF00000>;
size = <0x0 0x80000>;
};
