/** @file
 * (Register definitions for GDB Stub and target description generator).
 */

/*
 * Copyright (C) 2008 Freescale Semiconductor, Inc.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN
 * NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Derived from:
 * PowerPC Register Definition Dumper, Version v2_6_0
 * Using Reglib-base library version: v10_1_0
 *     Reglib-core library version: v45_0_0
 *     Reglib-device library version: v16_0_0
 */

struct register_description
{
	char *description;
	char *name;
	char *bitsize;
	char *regnum;
	char *save_restore;
	char *type;
	char *group;
};

struct register_description e500mc_registers[] =
{
#define R0_INDEX 0
	{ .name="r0", .bitsize="32", .type="uint32", },
	{ .name="r1", .bitsize="32", .type="uint32", },
	{ .name="r2", .bitsize="32", .type="uint32", },
	{ .name="r3", .bitsize="32", .type="uint32", },
	{ .name="r4", .bitsize="32", .type="uint32", },
	{ .name="r5", .bitsize="32", .type="uint32", },
	{ .name="r6", .bitsize="32", .type="uint32", },
	{ .name="r7", .bitsize="32", .type="uint32", },
	{ .name="r8", .bitsize="32", .type="uint32", },
	{ .name="r9", .bitsize="32", .type="uint32", },
	{ .name="r10", .bitsize="32", .type="uint32", },
	{ .name="r11", .bitsize="32", .type="uint32", },
	{ .name="r12", .bitsize="32", .type="uint32", },
	{ .name="r13", .bitsize="32", .type="uint32", },
	{ .name="r14", .bitsize="32", .type="uint32", },
	{ .name="r15", .bitsize="32", .type="uint32", },
	{ .name="r16", .bitsize="32", .type="uint32", },
	{ .name="r17", .bitsize="32", .type="uint32", },
	{ .name="r18", .bitsize="32", .type="uint32", },
	{ .name="r19", .bitsize="32", .type="uint32", },
	{ .name="r20", .bitsize="32", .type="uint32", },
	{ .name="r21", .bitsize="32", .type="uint32", },
	{ .name="r22", .bitsize="32", .type="uint32", },
	{ .name="r23", .bitsize="32", .type="uint32", },
	{ .name="r24", .bitsize="32", .type="uint32", },
	{ .name="r25", .bitsize="32", .type="uint32", },
	{ .name="r26", .bitsize="32", .type="uint32", },
	{ .name="r27", .bitsize="32", .type="uint32", },
	{ .name="r28", .bitsize="32", .type="uint32", },
	{ .name="r29", .bitsize="32", .type="uint32", },
	{ .name="r30", .bitsize="32", .type="uint32", },
	{ .name="r31", .bitsize="32", .type="uint32", },

#define F0_INDEX 32
	{ .name="f0", .bitsize="64", .type="ieee_double", .regnum="32" },
	{ .name="f1", .bitsize="64", .type="ieee_double", },
	{ .name="f2", .bitsize="64", .type="ieee_double", },
	{ .name="f3", .bitsize="64", .type="ieee_double", },
	{ .name="f4", .bitsize="64", .type="ieee_double", },
	{ .name="f5", .bitsize="64", .type="ieee_double", },
	{ .name="f6", .bitsize="64", .type="ieee_double", },
	{ .name="f7", .bitsize="64", .type="ieee_double", },
	{ .name="f8", .bitsize="64", .type="ieee_double", },
	{ .name="f9", .bitsize="64", .type="ieee_double", },
	{ .name="f10", .bitsize="64", .type="ieee_double", },
	{ .name="f11", .bitsize="64", .type="ieee_double", },
	{ .name="f12", .bitsize="64", .type="ieee_double", },
	{ .name="f13", .bitsize="64", .type="ieee_double", },
	{ .name="f14", .bitsize="64", .type="ieee_double", },
	{ .name="f15", .bitsize="64", .type="ieee_double", },
	{ .name="f16", .bitsize="64", .type="ieee_double", },
	{ .name="f17", .bitsize="64", .type="ieee_double", },
	{ .name="f18", .bitsize="64", .type="ieee_double", },
	{ .name="f19", .bitsize="64", .type="ieee_double", },
	{ .name="f20", .bitsize="64", .type="ieee_double", },
	{ .name="f21", .bitsize="64", .type="ieee_double", },
	{ .name="f22", .bitsize="64", .type="ieee_double", },
	{ .name="f23", .bitsize="64", .type="ieee_double", },
	{ .name="f24", .bitsize="64", .type="ieee_double", },
	{ .name="f25", .bitsize="64", .type="ieee_double", },
	{ .name="f26", .bitsize="64", .type="ieee_double", },
	{ .name="f27", .bitsize="64", .type="ieee_double", },
	{ .name="f28", .bitsize="64", .type="ieee_double", },
	{ .name="f29", .bitsize="64", .type="ieee_double", },
	{ .name="f30", .bitsize="64", .type="ieee_double", },
	{ .name="f31", .bitsize="64", .type="ieee_double", },

#define PC_INDEX 64
	{ .name="pc", .bitsize="32", .type="code_ptr", .regnum="64" },
	{ .name="msr", .bitsize="32", .type="uint32", },
	{ .name="cr", .bitsize="32", .type="uint32", },
	{ .name="lr", .bitsize="32", .type="code_ptr", },
	{ .name="ctr", .bitsize="32", .type="uint32", },
	{ .name="xer", .bitsize="32", .type="uint32", },

#define FPSCR_INDEX 70
	{ .name="fpscr", .bitsize="32", .group="float", .regnum="70" },

#define E500MC_SPRS_START 71
	{ .description = "Alternate Time Base register Lower",
	  .name="atbl", .bitsize="32", .regnum="71", .save_restore="no",
	  .group="general", },
	{ .description = "Alternate Time Base register Upper",
	  .name="atbu", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Branch Unit Control and Status Register 0",
	  .name="bucsr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Core Device Control and Status Register 0",
	  .name="cdcsr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Critical Save/Restore Register 0",
	  .name="csrr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Critical Save/Restore Register 1",
	  .name="csrr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Count Register",
	  .name="ctr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Data Address Compare 1",
	  .name="dac1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Data Address Compare 2",
	  .name="dac2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Control Register 0",
	  .name="dbcr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Control Register 1",
	  .name="dbcr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Control Register 2",
	  .name="dbcr2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Control Register 4",
	  .name="dbcr4", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Status Register",
	  .name="dbsr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Status Register Write Register",
	  .name="dbsrwr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Data Acquisition Message",
	  .name="ddam", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Data Exception Address Register",
	  .name="dear", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Decrementer",
	  .name="dec", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Decrementer Auto-Reload",
	  .name="decar", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Event Select Register",
	  .name="devent", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Save/Restore Register 0",
	  .name="dsrr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Debug Save/Restore Register 1",
	  .name="dsrr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Embedded Hypervisor Control and Status Register",
	  .name="ehcsr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "External PID Load Context Register",
	  .name="eplc", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "External Proxy Register",
	  .name="epr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "External PID Store Context Register",
	  .name="epsc", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Exception Syndrome Register",
	  .name="esr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Data Effective Address Register",
	  .name="gdear", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest External Proxy Register",
	  .name="gepr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Exception Syndrome Register",
	  .name="gesr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Interrupt Vector Offset Register 13",
	  .name="givor13", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Interrupt Vector Offset Register 14",
	  .name="givor14", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Interrupt Vector Offset Register 2",
	  .name="givor2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Interrupt Vector Offset Register 3",
	  .name="givor3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Interrupt Vector Offset Register 4",
	  .name="givor4", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Interrupt Vector Offset Register 8",
	  .name="givor8", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Interrupt Vector Prefix Register",
	  .name="givpr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Processor Identification Register",
	  .name="gpir", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Special Purpose Register General 0",
	  .name="gsprg0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Special Purpose Register General 1",
	  .name="gsprg1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Special Purpose Register General 2",
	  .name="gsprg2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Special Purpose Register General 3",
	  .name="gsprg3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Save Restore Register 0",
	  .name="gsrr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Guest Save Restore Register 1",
	  .name="gsrr1", .bitsize="32", .save_restore="no",
	  .group="general", },
#ifdef EXPOSE_HDBCRS
	/* Do not expose the hdbcr's. */
	{ .description = "Hardware Debug Control Register 0",
	  .name="hdbcr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Hardware Debug Control Register 1",
	  .name="hdbcr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Hardware Debug Control Register 2",
	  .name="hdbcr2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Hardware Debug Control Register 3",
	  .name="hdbcr3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Hardware Debug Control Register 4",
	  .name="hdbcr4", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Hardware Debug Control Register 5",
	  .name="hdbcr5", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Hardware Debug Control Register 6",
	  .name="hdbcr6", .bitsize="32", .save_restore="no",
	  .group="general", },
#endif
	{ .description = "Hardware Implementation-Dependent Register 0",
	  .name="hid0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Instruction Address Compare 1",
	  .name="iac1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Instruction Address Compare 2",
	  .name="iac2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 0 (Critical Input)",
	  .name="ivor0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 1 (Machine Check)",
	  .name="ivor1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 10 (Decrementer)",
	  .name="ivor10", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 11 "
			 "(Fixed-Interval Timer Interrupt)",
	  .name="ivor11", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 12 "
			 "(Watchdog Timer Interrupt)",
	  .name="ivor12", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 13 (Data TLB Error)",
	  .name="ivor13", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 14 "
			 "(Instruction TLB Error)",
	  .name="ivor14", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 15 (Debug)",
	  .name="ivor15", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 2 (Data Storage)",
	  .name="ivor2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 3 "
			 "(Instruction Storage)",
	  .name="ivor3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 35",
	  .name="ivor35", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 36",
	  .name="ivor36", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 37",
	  .name="ivor37", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 38",
	  .name="ivor38", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 39",
	  .name="ivor39", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 4 (External Input)",
	  .name="ivor4", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 40",
	  .name="ivor40", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 41",
	  .name="ivor41", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 5 (Alignment)",
	  .name="ivor5", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 6 (Program)",
	  .name="ivor6", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 7 "
			 "(Floating-Point Unavailable)",
	  .name="ivor7", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 8 (System Call)",
	  .name="ivor8", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Offset Register 9 "
			 "(Auxillary Processor Unavailable)",
	  .name="ivor9", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Interrupt Vector Prefix Register",
	  .name="ivpr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L1 Cache Configure Register 0",
	  .name="l1cfg0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L1 Cache Configure Register 1",
	  .name="l1cfg1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L1 Cache Control and Status Register 0",
	  .name="l1csr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L1 Cache Control and Status Register 1",
	  .name="l1csr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L1 Cache Control and Status Register 2",
	  .name="l1csr2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error data high capture register",
	  .name="l2captdatahi", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error data low capture register",
	  .name="l2captdatalo", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error capture ECC syndrome register",
	  .name="l2captecc", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache Configuration Register",
	  .name="l2cfg0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache Control and Status Register",
	  .name="l2csr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache Control and Status Register 1",
	  .name="l2csr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error address capture register",
	  .name="l2erraddr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error attributes register",
	  .name="l2errattr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error control register",
	  .name="l2errctl", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache Error Detect Register",
	  .name="l2errdet", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache Error Disable Register",
	  .name="l2errdis", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache Error extended address capture register",
	  .name="l2erreaddr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error injection control register",
	  .name="l2errinjctl", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error injection mask high register",
	  .name="l2errinjhi", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error injection mask low register",
	  .name="l2errinjlo", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "L2 Cache error interrupt enable register",
	  .name="l2errinten", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Logical Partition ID Format Register",
	  .name="lpidr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Link Register",
	  .name="lr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 0",
	  .name="mas0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 1",
	  .name="mas1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 2",
	  .name="mas2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 3",
	  .name="mas3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 4",
	  .name="mas4", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 5",
	  .name="mas5", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 6",
	  .name="mas6", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 7",
	  .name="mas7", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Assist Register 8",
	  .name="mas8", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Machine Check Address Register",
	  .name="mcar", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Machine Check Address Register Upper",
	  .name="mcaru", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Machine Check Syndrome Register",
	  .name="mcsr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Machine Check Save/Restore Register 0",
	  .name="mcsrr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Machine Check Save/Restore Register 1",
	  .name="mcsrr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Configuration Register",
	  .name="mmucfg", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MMU Control and Status Register 0",
	  .name="mmucsr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "MSR Protect Register",
	  .name="msrp", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus Processor ID Register",
	  .name="npidr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus SPR Access Configuration Register",
	  .name="nspc", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus SPR Access Data Register",
	  .name="nspd", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Process ID Register 0",
	  .name="pid0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Processor ID Register",
	  .name="pir", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Processor Version Register",
	  .name="pvr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 0",
	  .name="sprg0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 1",
	  .name="sprg1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 2",
	  .name="sprg2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 3",
	  .name="sprg3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 4",
	  .name="sprg4", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 5",
	  .name="sprg5", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 6",
	  .name="sprg6", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General 7",
	  .name="sprg7", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General Register 8",
	  .name="sprg8", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "SPR General Register 9",
	  .name="sprg9", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Save/Restore Register 0",
	  .name="srr0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Save/Restore Register 1",
	  .name="srr1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "System Version Register",
	  .name="svr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Supervisor Time Base Lower",
	  .name="tbl", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Supervisor Time Base Upper",
	  .name="tbu", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Timer Control Register",
	  .name="tcr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "TLB Configuration Register 0",
	  .name="tlbcfg0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "TLB Configuration Register 1",
	  .name="tlbcfg1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Timer Status Register",
	  .name="tsr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User SPR General 0",
	  .name="usprg0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User SPR General 3",
	  .name="usprg3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User SPR General 4",
	  .name="usprg4", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User SPR General 5",
	  .name="usprg5", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User SPR General 6",
	  .name="usprg6", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User SPR General 7",
	  .name="usprg7", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Time Base Lower",
	  .name="utbl", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Time Base Upper",
	  .name="utbu", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Integer Exception Register",
	  .name="xer", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Floating Point Status and Control Register",
	  .name="fpscr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Condition Code Register",
	  .name="cr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Machine State Register",
	  .name="msr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Next Instruction Address",
	  .name="nia", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Current Instruction Address",
	  .name="cia", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Reservation register",
	  .name="resrv", .bitsize="64", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Counter Register 0",
	  .name="pmc0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Counter Register 1",
	  .name="pmc1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Counter Register 2",
	  .name="pmc2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Counter Register 3",
	  .name="pmc3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Global Control Register 0",
	  .name="pmgc0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control A Register 0",
	  .name="pmlca0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control A Register 1",
	  .name="pmlca1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control A Register 2",
	  .name="pmlca2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control A Register 3",
	  .name="pmlca3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control B Register 0",
	  .name="pmlcb0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control B Register 1",
	  .name="pmlcb1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control B Register 2",
	  .name="pmlcb2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Performance Monitor Local Control B Register 3",
	  .name="pmlcb3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Counter Register 0",
	  .name="upmc0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Counter Register 1",
	  .name="upmc1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Counter Register 2",
	  .name="upmc2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Counter Register 3",
	  .name="upmc3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Global Control Register 0",
	  .name="upmgc0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control A Register 0",
	  .name="upmlca0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control A Register 1",
	  .name="upmlca1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control A Register 2",
	  .name="upmlca2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control A Register 3",
	  .name="upmlca3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control B Register 0",
	  .name="upmlcb0", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control B Register 1",
	  .name="upmlcb1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control B Register 2",
	  .name="upmlcb2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "User Performance Monitor Local Control B Register 3",
	  .name="upmlcb3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus Development Control Register 1",
	  .name="dc1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus Development Control Register 2",
	  .name="dc2", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus Development Control Register 3",
	  .name="dc3", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus Overrun Control Register",
	  .name="ovcr", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus Watchpoint Mask Register",
	  .name="wmsk", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Nexus Watchpoint Trigger Register 1",
	  .name="wt1", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "Pseudo-reg for e500mc's rst_base signals "
			 "(6 msb of default page)",
	  .name="rst_base", .bitsize="32", .save_restore="no",
	  .group="general", },
	{ .description = "External Debug Control Register 0",
	  .name="edbcr0", .bitsize="32", .save_restore="no",
	  .group="general", },
};

#define REG_COUNT sizeof(e500mc_registers)/sizeof(e500mc_registers[0])
