#!/usr/bin/expect -f

#
# Copyright (C) 2010 Freescale Semiconductor, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN
#  NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

log_user 0

# set timeout (seconds)
set timeout 360

spawn ../../tools/mux_server/mux_server localhost:9124 9000 9001 9002
set mux_id $spawn_id

spawn simics ../../test/linux/run-2p.simics
set simics_id $spawn_id

spawn socat -,raw,echo=0 tcp:localhost:9000
set ch0_id $spawn_id

spawn socat -,raw,echo=0 tcp:localhost:9001
set ch1_id $spawn_id

spawn socat -,raw,echo=0 tcp:localhost:9002
set ch2_id $spawn_id

set spawn_id $simics_id
expect {
	"simics>" {send "c\r"}
	timeout {
		send_user "FAIL: couldn't start simics\n"
		exit 1
	}
}

# partition1 - look for linux prompt
set spawn_id $ch1_id
expect {
	"p4080 login:" {}
	timeout {
		send_user "FAIL: P1 timeout\n"
		exit 1
	}
}

# partition2 - look for linux prompt
set spawn_id $ch2_id
expect {
	"p4080 login:" {}
	timeout {
		send_user "FAIL: P2 timeout\n"
		exit 1
	}
}

send_user "linux-2p: PASS\n"

exit 0
